### ISSUE TITLE
kmp是啥。。。

### ISSUE THREAD

**Issue by nondanee** [jcuan/data_structure#1]
完蛋了，我发现我做王道的时候直接给跳过了。。。因为感觉没学过=。=

**Comment by jcuan** [comment]
字符串的模式匹配那儿的，我也是跳过了，不过刚发现大纲上是要求字符串的模式匹配的，2005年还考过那个求next

**Comment by nondanee** [comment]
emmmm好吧我也去写了下https://github.com/nondanee/algorithm-review/blob/master/kmp.py
